from .fractions import TEMPLATES as FRACTION_TEMPLATES
from .multiplication import TEMPLATES as MULTIPLICATION_TEMPLATES
from .addition_subtraction import TEMPLATES as ADD_SUB_TEMPLATES
from .division import TEMPLATES as DIVISION_TEMPLATES
from .decimals import TEMPLATES as DECIMAL_TEMPLATES
from .measurement import TEMPLATES as MEASUREMENT_TEMPLATES
from .geometry import TEMPLATES as GEOMETRY_TEMPLATES
from .statistics import TEMPLATES as STATISTICS_TEMPLATES

TEMPLATES = (
    FRACTION_TEMPLATES
    + MULTIPLICATION_TEMPLATES
    + ADD_SUB_TEMPLATES
    + DIVISION_TEMPLATES
    + DECIMAL_TEMPLATES
    + MEASUREMENT_TEMPLATES
    + GEOMETRY_TEMPLATES
    + STATISTICS_TEMPLATES
)

__all__ = ["TEMPLATES"]
