from .fractions import TEMPLATES as FRACTION_TEMPLATES
from .multiplication import TEMPLATES as MULTIPLICATION_TEMPLATES

TEMPLATES = FRACTION_TEMPLATES + MULTIPLICATION_TEMPLATES

__all__ = ["TEMPLATES"]
